version: '3.6'
services:
  alpine:
    image: alpine:latest
    container_name: alpine
    command: sh -c 'tail -f /dev/null'

  telegraf:
    image: telegraf:1.18-alpine
    container_name: telegraf
    volumes:
    - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:rw
    - ./telegraf/etc:/etc/telegraf
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '127.0.0.1:8125:8125/udp'

  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    ports:
      - '127.0.0.1:8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:7.5.4
    container_name: grafana
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/

volumes:
  grafana_data: {}
  influxdb_data: {}
